name: Build and Deploy Docker Image

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      custom_tags:
        description: 'Custom Docker tags (comma-separated for multiple tags)'
        required: false
        default: '0.1.1'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build images with docker-build
        run: docker build

      - name: Tag and push images
        run: |
          CUSTOM_TAGS="${{ github.event.inputs.custom_tags }}"
          if [ -z "$CUSTOM_TAGS" ]; then
            CUSTOM_TAGS="0.1.1"
          fi
          IFS=',' read -ra TAGS <<< "$CUSTOM_TAGS"

          for TAG in "${TAGS[@]}"; do
            docker tag second-wave:latest nadigatlaparimala/second-wave:$TAG
            docker push nadigatlaparimala/second-wave:$TAG
          done